version: '3'
services:
  web:
    container_name: studio-center-auditions-dev
    restart: always
    build: .
    links:
     - db
     - adminmongo
     - redis
    ports:
     - "3000:3000"
     - '80:3000'
     - '35729:35729'
    environment:
      NODE_ENV: development

  db:
    container_name: mongo
    image: mongo
    volumes:
     - ./data/db:/data/db
    ports:
     - "27017:27017"

  adminmongo:
    image: 'mrvautin/adminmongo'
    ports:
      - "1234:1234"

  redis:
    container_name: studio-center-auditions-redis
    image: 'redis:4.0.11'
    expose:
      - 6379
